### PR TITLE
Creator Portal: Uploading and Managing Content 

### PR DESCRIPTION
**Pull request by minikin**
## 🚀 In this PR
- [x] Users can register with email and password
- [x] Users can sign in with email and password
- [x] Users can explore audio content
- [x] Users can create and upload audio files with cover to Firebase
- [x] Users can delete audio content
- [x] Loading indicator while uploading _(We'll update implementation #234)_
- [x] Error handling and user notification via snackbars messages
- [x] Spot Holder For Upload Track Web Portal #233 
- [x] Users can also select to delete content. When they do, this notification will pop up. #262
- [x] Users can edit Audio Content. #263

## 🔜 Not in this PR

- Sort media content by uploading date 

## ⚠️ BREAKING CHANGES
- Audio Files are stored to `audio_files` folder 
- Audio Covers are stored to `audio_files` folder 

## ⛑ TODO
**Please, test the app on iOS, Android, and Web after #264 will be implemented.**

### CODE REVIEW

**Comment by minikin** [comment]
**DO NOT MERGE THIS BRANCH YET!**

**Comment by minikin** [comment]
I think we need to discuss it publically: @7flash @JasonHighVibe 
>Crypto 🌱❤️🌱 Igor, [25. Jul 2020 at 06:32:05]:
>What you mean by conditional compilation?
>
>I'd prefer NOT to have conditions like
>
>if (isWeb) Widget1() else Widget2();
>
>But rather have separate routes for web and mobile
>
>Please, I am asking that from my experience with https://github.com/swaponline/MultiCurrencyWallet - that became >unmaintainable mess after implementation of widget/full mode

You can read about "Conditional Compilation" in the issue description, it's not about widgets #264 

Regarding conditional rendering for widgets for different platforms:
I think it's a totally valid approach because:
1. Web Portal has a completely different UI/UX
2. It's common practice to have conditional rendering for different platforms (mobile, web, desktop) in Google/Flutter production codebase.

In issue #215, we didn't mention any particular approach on how to handle the platform-specific code for the web portal. 
So, I decided to implement in Google's and Flutter's team recommendations way.

**We should consider discussing such a technical decision in advance and document decisions in the wiki.**
Such a procedure will save a lot of time and will keep high morale and will improve the collaborative atmosphere in the team.

Additional notes:
- The idea to have separate routes for mobile and web sounds like an antipattern to me at this point. But that's probably because I don't understand the idea in detail.
- We have only a couple of widgets which depend on platform-specific code: 
    - [GradientRaisedButton](https://github.com/HighVibe/hvn/blob/feature/sp-215/lib/widgets/gradient_raised_button.dart) uses of LinearGradient and it's simply crash web-portal, so I remove unnecessary computation and replaced it with image, plus applied a few small tweaks to adjust to UI/UX specification for web-portal.
    - Initial loading animation doesn't display on the web-portal because Lottie is not completely supported for the web now, as I understand.

**Comment by JasonHighVibe** [comment]
We're going to pull some other perspectives on this one;

@AlexVegner

> I think we need to discuss it publically: @7flash @JasonHighVibe
> 
> > Crypto 🌱❤️🌱 Igor, [25. Jul 2020 at 06:32:05]:
> > What you mean by conditional compilation?
> > I'd prefer NOT to have conditions like
> > if (isWeb) Widget1() else Widget2();
> > But rather have separate routes for web and mobile
> > Please, I am asking that from my experience with https://github.com/swaponline/MultiCurrencyWallet - that became unmaintainable mess after implementation of widget/full mode
> 
> You can read about "Conditional Compilation" in the issue description, it's not about widgets #264
> 
> Regarding conditional rendering for widgets for different platforms:
> I think it's a totally valid approach because:
> 
> 1. Web Portal has a completely different UI/UX
> 2. It's common practice to have conditional rendering for different platforms (mobile, web, desktop) in Google/Flutter production codebase.
> 
> In issue #215, we didn't mention any particular approach on how to handle the platform-specific code for the web portal.
> So, I decided to implement in Google's and Flutter's team recommendations way.
> 
> **We should consider discussing such a technical decision in advance and document decisions in the wiki.**
> Such a procedure will save a lot of time and will keep high morale and improve the collaborative atmosphere in the team.
> 
> Additional notes:
> 
> * The idea to have separate routes for mobile and web sounds like an antipattern to me at this point. But that's probably because I don't understand the idea in detail.
> * We have only a couple of widgets which depend on platform-specific code:
>   
>   * [GradientRaisedButton](https://github.com/HighVibe/hvn/blob/feature/sp-215/lib/widgets/gradient_raised_button.dart) uses of LinearGradient and it's simply crash web-portal, so I remove unnecessary computation and replaced it with image, plus applied a few small tweaks to adjust to UI/UX specification for web-portal.
>   * Initial loading animation doesn't display on the web-portal because Lottie is not completely supported for the web now, as I understand.

**Comment by minikin** [comment]
Please, read my [comment](https://github.com/HighVibe/hvn/issues/264#issuecomment-665522484).

**Pull request merged**
