### PR TITLE
Feature: Effective Dart

### PR DESCRIPTION
**Pull request by minikin**
- Update Flutter to [1.17.2](https://groups.google.com/forum/#!topic/flutter-dev/CrxAD3zE8q8) and Dart to [2.8.3](https://groups.google.com/a/dartlang.org/forum/#!topic/misc/hzorLYufW-M)
- Introduce [Effective Dart](https://dart.dev/guides/language/effective-dart) to the project
- Update [analysis_options.yaml](https://github.com/HighVibe/hvn/blob/feature/sp-125/analysis_options.yaml) to follow Effective Dart
- Fix about 800 errors and warnings (You probably don't need to review all files because updates are quite repetitive.)

Let's discuss rules in `analysis_options.yaml` which we can relax or add a more strict one.

After a discussion, we have to consider enabling `Branch protection rule -> Require status checks to pass before merging` if it does not enable yet.

### CODE REVIEW

**Comment by minikin** [comment]
I'll fix CI in the next commit.

**Comment by minikin** [comment]
@7flash 
We have only warnings left:

```sh
 info • The type of firestore can't be inferred; a type must be explicitly provided • lib/services/firestore_service.dart:10:20 • inference_failure_on_untyped_parameter
```
Can you please, fix it?

We can start a discussion.

**Comment by minikin** [comment]
@7flash LGTM

**Comment by 7flash** [comment]
Screenshot_2020-06-02_09-49-19

**Pull request merged**
