### PR TITLE
Change User model

### PR DESCRIPTION
**Pull request by divyanshub024**

### CODE REVIEW

**Comment by minikin** [comment]
@divyanshub024 What's the reason behind that you decided to move from value to types to your implementation?

**Comment by divyanshub024** [comment]
@minikin There are multiple reasons. 

1. It's simple to use and have less boilerplate code. 

2. It solved a few errors which were coming like
```
Unhandled Exception: Converting an object to an encodable object failed: Instance of 'Timestamp'
```
These kinds of errors were coming because we were converting firebase snapshot to JSON and then fromJson to model. Instead of that, we can just do what we are doing right now. 
Firebase models don't need to be converted from JSON or to JSON. 

3. This is the correct way of creating firebase models as shown in different examples, documentations and code labs. 
https://codelabs.developers.google.com/codelabs/flutter-firebase/#10

**Comment by divyanshub024** [comment]
Also, PR is not complete yet. I just pushed it so I can get yours and @7flash views about it.

**Comment by minikin** [comment]
@divyanshub024 

## 1. 
Actually, that's the opposite.
- Built value [generates a huge amount of code for free](https://github.com/HighVibe/hvn/blob/master/lib/models/user/user.g.dar)
- Built values are value types(immutable values) and not reference types [1](https://en.wikipedia.org/wiki/Value_type_and_reference_type), [2](https://www.raywenderlich.com/9481-reference-vs-value-types-in-swiftt), [3](https://www.tutorialsteacher.com/csharp/csharp-value-type-and-reference-type)  . Consequently, it's faster. 
- JSON object serialization and deserialization (**generated for free**)
- HashCode properties (**generated for free**)
- Objects equality (**generated for free**)
- toString methods (**generated for free**)
- Getter memoization  (**generated for free**)
- [EnumClass](https://www.geeksforgeeks.org/enum-classes-in-c-and-their-advantage-over-enum-datatype/)
- Dramatically improves [testability](https://pub.dev/packages/built_value_test)
- Tooling  - [VSCode extension](https://marketplace.visualstudio.com/items?itemName=GiancarloCode.built-value-snippets), [IntelliJ plugin](https://plugins.jetbrains.com/plugin/13786-built-value-snippets)
- Has companion pub [built_collection](https://pub.dev/packages/built_collection) for collections
- And [more](https://pub.dev/packages/built_value)

Last but not least, [built_value](https://pub.dev/packages/built_value) widely used in products like Google AdWords.

### Articles

- [`built_value` for Immutable Object Models](https://medium.com/@davidmorgan_14314/darts-built-value-for-immutable-object-models-83e2497922d4#.48dyezxcl)
- [`built_value` for Serialization](https://medium.com/@davidmorgan_14314/darts-built-value-for-serialization-f5db9d0f4159#.h12y94wu7)
- [Building a Chat App in Dart](https://medium.com/@davidmorgan_14314/building-a-chat-app-in-dart-815fcd0e5a31#.ku4vtbmk2)
- [End to End Testing in One Short Second with Dart](https://medium.com/@davidmorgan_14314/end-to-end-testing-in-one-short-second-with-dart-e699c8146fd6#.c7xfxohg4)
- [Moving Fast with Dart Immutable Values](https://medium.com/@davidmorgan_14314/moving-fast-with-dart-immutable-values-1e717925fafb)
- [Flutter JSON Serialization](https://aloisdeniel.github.io/flutter-json-serialization/)
- [Flutter TODO App Example](https://gitlab.com/brianegan/flutter_architecture_samples/tree/master/example/built_redux)
  using `built_value`, [built_redux](https://pub.dev/packages/built_redux), and [flutter_built_redux](https://pub.dev/packages/flutter_built_redux)
- [Building a (large) Flutter app with Redux](https://hillelcoren.com/2018/06/01/building-a-large-flutter-app-with-redux/)
- [Some Options for Deserializing JSON with Flutter](https://medium.com/flutter-io/some-options-for-deserializing-json-with-flutter-7481325a4450)

### Tutorials

 - [Custom Serializers](https://medium.com/@solid.goncalo/creating-custom-built-value-serializers-with-builtvalueserializer-46a52c75d4c5)
 - [Flutter + built_value + Reddit Tutorial](https://steemit.com/utopian-io/@tensor/building-immutable-models-with-built-value-and-built-collection-in-dart-s-flutter-framework);
   [video](https://www.youtube.com/watch?v=hNbOSSgpneI);
   [source code](https://github.com/tensor-programming/built_flutter_tutorial)


## 2. 
The error caused because Firebase doesn't support automatic model migrations. Some user's accounts have an old model. To fix it we just need to delete old records (user documents on Firebase). 

We need to parse to JSON and from JSON with Firebase. 
Firebase sends proto buffers over wires but it represents objects to us in JSON format. If you check codelab example more carefully, you'll notice that in class `Record` there is a method `fromMap`. That's where a JSON parsing happens.

```dart
class Record {
 final String name;
 final int votes;
 final DocumentReference reference;

 Record.fromMap(Map<String, dynamic> map, {this.reference})
     : assert(map['name'] != null),
       assert(map['votes'] != null),
       name = map['name'],
       votes = map['votes'];

 Record.fromSnapshot(DocumentSnapshot snapshot)
     : this.fromMap(snapshot.data, reference: snapshot.reference);

 @override
 String toString() => "Record<$name:$votes>";
}
```

## 3. 
Codelabs are for developers who want to start quickly and usually are not production-quality code examples.

Method `fromMap` is a great example of it:
`Record.fromMap(Map<String, dynamic> map, {this.reference})`

The `dynamic` type is the heritage of Dart 1 when Dart was dynamically typed language. In modern Dart 2, which is statically typed, it's not good practice to use dynamic. The `object` type is preferable.

**Comment by divyanshub024** [comment]
Thanks a lot for this info. But how exactly this way can cause an issue with production-quality code.

**Comment by minikin** [comment]
@divyanshub024 I'm not quite sure that I understand what are you asking. Can you clarify it, please?

**Pull request closed without merging**
